        !COMPILER-GENERATED INTERFACE MODULE: Fri May 08 18:48:49 2015
        MODULE ABOUTDLGPROC__genmod
          INTERFACE 
            FUNCTION ABOUTDLGPROC(HDLG,MESSAGE,UPARAM,LPARAM)
              INTEGER(KIND=4) :: HDLG
              INTEGER(KIND=4) :: MESSAGE
              INTEGER(KIND=4) :: UPARAM
              INTEGER(KIND=4) :: LPARAM
              INTEGER(KIND=4) :: ABOUTDLGPROC
            END FUNCTION ABOUTDLGPROC
          END INTERFACE 
        END MODULE ABOUTDLGPROC__genmod
