        !COMPILER-GENERATED INTERFACE MODULE: Fri May 08 18:48:48 2015
        MODULE CENTERWINDOW__genmod
          INTERFACE 
            SUBROUTINE CENTERWINDOW(HWNDCHILD,HWNDPARENT)
              INTEGER(KIND=4) :: HWNDCHILD
              INTEGER(KIND=4) :: HWNDPARENT
            END SUBROUTINE CENTERWINDOW
          END INTERFACE 
        END MODULE CENTERWINDOW__genmod
