        !COMPILER-GENERATED INTERFACE MODULE: Fri May 08 18:48:49 2015
        MODULE INPUT__genmod
          INTERFACE 
            SUBROUTINE INPUT
            END SUBROUTINE INPUT
          END INTERFACE 
        END MODULE INPUT__genmod
