        !COMPILER-GENERATED INTERFACE MODULE: Fri May 08 18:48:49 2015
        MODULE MAINWNDPROC__genmod
          INTERFACE 
            FUNCTION MAINWNDPROC(HWND,MESG,WPARAM,LPARAM)
              INTEGER(KIND=4) :: HWND
              INTEGER(KIND=4) :: MESG
              INTEGER(KIND=4) :: WPARAM
              INTEGER(KIND=4) :: LPARAM
              INTEGER(KIND=4) :: MAINWNDPROC
            END FUNCTION MAINWNDPROC
          END INTERFACE 
        END MODULE MAINWNDPROC__genmod
