        !COMPILER-GENERATED INTERFACE MODULE: Fri May 08 18:48:48 2015
        MODULE OFNTEST1__genmod
          INTERFACE 
            SUBROUTINE OFNTEST1(FILE_SPEC)
              CHARACTER(LEN=1) :: FILE_SPEC
            END SUBROUTINE OFNTEST1
          END INTERFACE 
        END MODULE OFNTEST1__genmod
