        !COMPILER-GENERATED INTERFACE MODULE: Fri May 08 18:48:48 2015
        MODULE OFNTEST__genmod
          INTERFACE 
            SUBROUTINE OFNTEST
            END SUBROUTINE OFNTEST
          END INTERFACE 
        END MODULE OFNTEST__genmod
