        !COMPILER-GENERATED INTERFACE MODULE: Fri May 08 18:48:48 2015
        MODULE PLOT2__genmod
          INTERFACE 
            SUBROUTINE PLOT2(RMAX,GTITLE,XTITLE,YTITLE,CDEV,COLORG,SPWF)
              INTEGER(KIND=4) :: RMAX
              CHARACTER(LEN=30) :: GTITLE
              CHARACTER(LEN=30) :: XTITLE
              CHARACTER(LEN=30) :: YTITLE
              CHARACTER(LEN=4) :: CDEV
              CHARACTER(LEN=4) :: COLORG
              CHARACTER(LEN=13) :: SPWF
            END SUBROUTINE PLOT2
          END INTERFACE 
        END MODULE PLOT2__genmod
