        !COMPILER-GENERATED INTERFACE MODULE: Fri May 08 18:48:48 2015
        MODULE PP_SHELL__genmod
          INTERFACE 
            SUBROUTINE PP_SHELL(FILENAME1,IU,NOJMA)
              CHARACTER(LEN=12) :: FILENAME1
              INTEGER(KIND=4) :: IU
              INTEGER(KIND=4) :: NOJMA
            END SUBROUTINE PP_SHELL
          END INTERFACE 
        END MODULE PP_SHELL__genmod
