        !COMPILER-GENERATED INTERFACE MODULE: Fri May 08 18:48:49 2015
        MODULE SPDENSITY__genmod
          INTERFACE 
            SUBROUTINE SPDENSITY
            END SUBROUTINE SPDENSITY
          END INTERFACE 
        END MODULE SPDENSITY__genmod
