        !COMPILER-GENERATED INTERFACE MODULE: Fri May 08 18:48:48 2015
        MODULE TH_FACINIT__genmod
          INTERFACE 
            SUBROUTINE TH_FACINIT
            END SUBROUTINE TH_FACINIT
          END INTERFACE 
        END MODULE TH_FACINIT__genmod
