        !COMPILER-GENERATED INTERFACE MODULE: Fri May 08 18:48:49 2015
        MODULE TRCHARGEDENSITY__genmod
          INTERFACE 
            SUBROUTINE TRCHARGEDENSITY
            END SUBROUTINE TRCHARGEDENSITY
          END INTERFACE 
        END MODULE TRCHARGEDENSITY__genmod
