        !COMPILER-GENERATED INTERFACE MODULE: Fri May 08 18:48:46 2015
        MODULE WINMAIN__genmod
          INTERFACE 
            FUNCTION WINMAIN(HINSTANCE,HPREVINSTANCE,LPSZCMDLINE,       &
     &NCMDSHOW)
              INTEGER(KIND=4) :: HINSTANCE
              INTEGER(KIND=4) :: HPREVINSTANCE
              INTEGER(KIND=4) :: LPSZCMDLINE
              INTEGER(KIND=4) :: NCMDSHOW
              INTEGER(KIND=4) :: WINMAIN
            END FUNCTION WINMAIN
          END INTERFACE 
        END MODULE WINMAIN__genmod
